from odoo import models

class AmazonCustomerExcel(models.Model):
    _name = 'report.amazon.amazon_customer_report_xls'
    _inherit = 'report.report_xlsx.abstract'

    def generate_xlsx_report(self, workbook, data, user):
        sheet = workbook.add_worksheet('Customer Records')
        bold = workbook.add_format({'bold': True})
        text_center = workbook.add_format({'align': 'center'})
        format_1 = workbook.add_format({'bold': True, 'align': 'right'})
        format_3 = workbook.add_format({'bold': True, 'align': 'center'})
        format_2 = workbook.add_format({'align': 'top'})

        sheet.set_column('A:A', 10)
        sheet.set_column('B:B', 25)
        sheet.set_column('C:C', 20)
        sheet.set_column('D:D', 15)
        sheet.set_column('E:E', 25)
        sheet.set_column('E:E', 10)
        sheet.set_column('F:F', 10)
        sheet.set_column('G:G', 25)
        sheet.set_column('H:H', 12)

        sheet.write('A3', 'Exporter:', bold)
        sheet.merge_range(2, 1, 7, 2, 'Visotec Corporate Identity Solutions Private Limited Building No. B-200-A, Indospace Industrial Park', format_2)
        # sheet.write('B3', 'Visotec Corporate Identity Solutions Private Limited')
        # sheet.write('C3', '')
        sheet.merge_range(2, 3, 2, 4, 'Invoice No. & Date')
        # sheet.write('D3', 'Invoice No. & Date', bold)
        # sheet.write('E3', '')
        sheet.merge_range(2, 5, 2, 6, '')
        # sheet.write('F3', '')
        # sheet.write('G3', '')
        sheet.write('H3', 'Exporters IEC', bold)
        sheet.write('A4', '')
        # sheet.merge_range(3, 1, 3, 2, 'Building No. B-200-A, Indospace Industrial Park')
        # sheet.write('B4', 'Building No. B-200-A, Indospace Industrial Park,')
        sheet.write('C4', '')
        sheet.write('D4', '')
        sheet.write('E4', '')
        sheet.merge_range(3, 5, 3, 6, '')
        # sheet.write('F4', '')
        # sheet.write('G4', '')
        sheet.write('H4', 'AAHCV3380J', bold)
        sheet.write('A5', '')
        # sheet.write('B5', 'Chakan II, Gat No-341, Mahalunge,')
        # sheet.write('C5', '')
        sheet.write('D5', '')
        sheet.write('E5', '')
        sheet.write('F5', '')
        sheet.write('G5', 'Shipping Line:', bold)
        sheet.write('H5', '')
        sheet.write('A6', '')
        # sheet.write('B6', 'Khed Taluka, Pune Maharashtra 410501 India')
        # sheet.write('C6', '')
        sheet.merge_range(5, 3, 5, 4, 'Buyers Order No. & Date')
        # sheet.write('D6', 'Buyers Order No. & Date', bold)
        # sheet.write('E6', '')
        sheet.write('F6', '')
        sheet.write('G6', 'Forwarder:', bold)
        sheet.write('H6', '')
        sheet.write('A7', '')
        # sheet.write('B7', 'Email: gaspard.debordas@alternative-india.com')
        # sheet.write('C7', '')
        sheet.write('D7', '')
        sheet.write('E7', '')
        sheet.write('F7', '')
        sheet.write('G7', 'Other Ref.', bold)
        sheet.write('H7', '')
        sheet.write('A8', '')
        # sheet.write('B8', 'GST No. 27AAHCV3380J1ZY')
        # sheet.write('C8', '')
        sheet.write('D8', '')
        sheet.write('E8', '')
        sheet.write('F8', '')
        sheet.write('G8', '')
        sheet.write('H8', '')

        sheet.write('A9', 'Consignee :-', bold)
        sheet.write('B9', '')
        sheet.write('C9', '')
        sheet.merge_range(8, 3, 8, 4, 'Country of Origin of Goods :')
        # sheet.write('D9', '')
        # sheet.write('E9', 'Country of Origin of Goods :', format_1)
        sheet.merge_range(8, 5, 8, 7, 'Pune, Maharashtra (India)')
        # sheet.write('F9', 'Pune, Maharashtra (India)', bold)
        # sheet.write('G9', '')
        # sheet.write('H9', '')
        sheet.write('A10', '')
        sheet.write('B10', '')
        sheet.write('C10', '')
        sheet.merge_range(9, 3, 9, 4, 'Port of Load :')
        # sheet.write('D10', '')
        # sheet.write('E10', 'Port of Load :', format_1)
        sheet.merge_range(9, 5, 9, 7, '')
        # sheet.write('F10', '')
        # sheet.write('G10', '')
        # sheet.write('H10', '')
        sheet.write('A11', '')
        sheet.write('B11', '')
        sheet.write('C11', '')
        sheet.merge_range(10, 3, 10, 4, 'Country of Final Destination :')
        # sheet.write('D11', '')
        # sheet.write('E11', 'Country of Final Destination :', format_1)
        sheet.merge_range(10, 5, 10, 7, '')
        # sheet.write('F11', '')
        # sheet.write('G11', '')
        # sheet.write('H11', '')
        sheet.write('A12', '')
        sheet.write('B12', '')
        sheet.write('C12', '')
        sheet.merge_range(11, 3, 11, 4, 'Port of Discharge :')
        # sheet.write('D12', '')
        # sheet.write('E12', 'Port of Discharge :', format_1)
        sheet.merge_range(11, 5, 11, 7, '')
        # sheet.write('F12', '')
        # sheet.write('G12', '')
        # sheet.write('H12', '')
        sheet.write('A13', '')
        sheet.write('B13', '')
        sheet.write('C13', '')
        sheet.merge_range(12, 3, 12, 4, 'Final Destination :')
        # sheet.write('D13', '')
        # sheet.write('E13', 'Final Destination :', format_1)
        sheet.merge_range(12, 5, 12, 7, '')
        # sheet.write('F13', '')
        # sheet.write('G13', '')
        # sheet.write('H13', '')
        sheet.write('A14', '')
        sheet.write('B14', '')
        sheet.write('C14', '')
        sheet.merge_range(13, 3, 13, 4, 'Incoterms')
        # sheet.write('D14', '')
        # sheet.write('E14', 'Incoterms', format_1)
        sheet.merge_range(13, 5, 13, 7, '')
        # sheet.write('F14', '')
        # sheet.write('G14', '')
        # sheet.write('H14', '')

        sheet.merge_range(14, 0, 14, 1, 'Marks & Nos  :')
        # sheet.write('A15', '')
        # sheet.write('B15', 'Marks & Nos  :', format_1)
        sheet.write('C15', '')
        sheet.merge_range(14, 3, 14, 4, 'Pre Carriage by :')
        # sheet.write('D15', '')
        # sheet.write('E15', 'Pre Carriage by :', format_1)
        sheet.merge_range(14, 5, 14, 7, '')
        # sheet.write('F15', '')
        # sheet.write('G15', '')
        # sheet.write('H15', '')
        sheet.merge_range(15, 0, 15, 1, 'Nos.& Kind of Packages :')
        # sheet.write('A16', '')
        # sheet.write('B16', 'Nos.& Kind of Packages :', format_1)
        sheet.write('C16', '')
        sheet.merge_range(15, 3, 15, 4, 'Total Net Weight Kg :')
        # sheet.write('D16', '')
        # sheet.write('E16', 'Total Net Weight Kg :', format_1)
        sheet.write('F16', '')
        sheet.write('G16', '')
        sheet.write('H16', '')
        sheet.merge_range(16, 0, 16, 1, 'Description of Goods :')
        # sheet.write('A17', '')
        # sheet.write('B17', 'Description of Goods :', format_1)
        sheet.write('C17', '')
        sheet.merge_range(16, 3, 16, 4, 'Total Gross Weight Kg :')
        # sheet.write('D17', '')
        # sheet.write('E17', 'Total Gross Weight Kg :', format_1)
        sheet.write('F17', '')
        sheet.write('G17', '')
        sheet.write('H17', '')

        sheet.write('A19', 'Line Number', format_3)
        sheet.write('B19', 'Part Number', format_3)
        sheet.write('C19', 'Description of Goods', format_3)
        sheet.write('D19', 'Nos. of Package', format_3)
        sheet.write('E19', 'HSN Code', format_3)
        sheet.write('F19', 'Total Qty', format_3)
        sheet.write('G19', 'Rate in Euro', format_3)
        sheet.write('H19', 'Amount in Euro', format_3)

        row = 19
        col = 0
        for obj in user:
            sheet.write(row, col, obj.age, text_center)
            col += 1
            sheet.write(row, col, obj.contact, text_center)
            col += 1
            sheet.write(row, col, obj.name, text_center)
            col += 1
            sheet.write(row, col, obj.gender, text_center)
            row += 1








